// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValachNorbert_TantargyakAPI.Data;

#nullable disable

namespace ValachNorbert_TantargyakAPI.Migrations
{
    [DbContext(typeof(TantargyContext))]
    partial class TantargyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ValachNorbert_TantargyakAPI.Models.Tanar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BelepesDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tanarok");
                });

            modelBuilder.Entity("ValachNorbert_TantargyakAPI.Models.Tantargy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EvesOraszam")
                        .HasColumnType("int");

                    b.Property<string>("RovidLeiras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TanarId")
                        .HasColumnType("int");

                    b.Property<string>("TantargyNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TanarId");

                    b.ToTable("Tantargyak");
                });

            modelBuilder.Entity("ValachNorbert_TantargyakAPI.Models.Tantargy", b =>
                {
                    b.HasOne("ValachNorbert_TantargyakAPI.Models.Tanar", "Tanar")
                        .WithMany("Tantargyak")
                        .HasForeignKey("TanarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tanar");
                });

            modelBuilder.Entity("ValachNorbert_TantargyakAPI.Models.Tanar", b =>
                {
                    b.Navigation("Tantargyak");
                });
#pragma warning restore 612, 618
        }
    }
}
